export const styleProfiles = {
  Pop: {
    tempoRange: [90, 120],
    drums: 'Clean 4/4, punchy kick, snappy snare or clap, light syncopation',
    instruments: 'Bright synths, piano, guitars, vocal chops',
    chords: 'Major, simple progressions, catchy hooks',
    bass: 'Tight supportive bass following roots with light movement',
    mix: 'Polished, bright, vocal-forward',
    keyBias: 'major',
    chordColor: 'simple',
    wave: 'triangle',
    drumFeel: 'clean',
    swing: 0.01,
    drumDrive: 0.78,
    padLevel: 0.18,
    melodyDensity: 0.82,
    brightness: 0.84,
    bassMovement: 0.42,
  },
  'R&B': {
    tempoRange: [60, 90],
    drums: 'Laid-back, swung hats, soft kicks, rimshots',
    instruments: 'Rhodes, pads, soft synth leads, guitars',
    chords: 'Extended 7ths and 9ths, smooth, jazzy',
    bass: 'Warm, melodic, gliding',
    mix: 'Warm, spacious, smooth highs',
    keyBias: 'mixed',
    chordColor: 'extended',
    wave: 'sine',
    drumFeel: 'laid-back',
    swing: 0.1,
    drumDrive: 0.48,
    padLevel: 0.28,
    melodyDensity: 0.56,
    brightness: 0.48,
    bassMovement: 0.7,
  },
  'Hip Hop (Boom Bap)': {
    tempoRange: [80, 100],
    drums: 'Hard kicks, dusty snares, swing-heavy',
    instruments: 'Samples, vinyl textures, horns, piano loops',
    chords: 'Minor-heavy, soulful loops',
    bass: 'Simple, gritty, groove-focused',
    mix: 'Punchy, mid-forward, raw edges',
    keyBias: 'minor',
    chordColor: 'soulful',
    wave: 'triangle',
    drumFeel: 'boom-bap',
    swing: 0.12,
    drumDrive: 0.88,
    padLevel: 0.16,
    melodyDensity: 0.48,
    brightness: 0.42,
    bassMovement: 0.38,
  },
  'Hip Hop (Trap)': {
    tempoRange: [130, 160],
    drums: '808s, rapid hi-hats, rolls, snappy snares',
    instruments: 'Dark synths, bells, plucks',
    chords: 'Minimal, minor, repetitive',
    bass: 'Heavy 808, sliding and gliding',
    mix: 'Sub-heavy, crisp highs',
    keyBias: 'minor',
    chordColor: 'minimal',
    wave: 'saw',
    drumFeel: 'trap',
    swing: 0.035,
    drumDrive: 0.92,
    padLevel: 0.14,
    melodyDensity: 0.4,
    brightness: 0.62,
    bassMovement: 0.82,
  },
  'Electronic / Dance': {
    tempoRange: [120, 140],
    drums: 'Steady four-on-the-floor, driving kicks',
    instruments: 'Synth leads, arps, pads',
    chords: 'Simple, uplifting or minor tension',
    bass: 'Driving, rhythmic',
    mix: 'Wide, loud, energetic',
    keyBias: 'mixed',
    chordColor: 'simple',
    wave: 'saw',
    drumFeel: 'four-on-floor',
    swing: 0.01,
    drumDrive: 0.95,
    padLevel: 0.2,
    melodyDensity: 0.76,
    brightness: 0.82,
    bassMovement: 0.64,
  },
  'Lo-Fi': {
    tempoRange: [60, 85],
    drums: 'Soft, dusty, low velocity',
    instruments: 'Rhodes, tape samples, vinyl crackle',
    chords: 'Jazzy, nostalgic',
    bass: 'Soft, rounded, subtle',
    mix: 'Warm, low-passed, imperfect',
    keyBias: 'mixed',
    chordColor: 'extended',
    wave: 'triangle',
    drumFeel: 'lo-fi',
    swing: 0.14,
    drumDrive: 0.36,
    padLevel: 0.3,
    melodyDensity: 0.44,
    brightness: 0.28,
    bassMovement: 0.46,
  },
  Soul: {
    tempoRange: [70, 105],
    drums: 'Live-feel pocket, rimshots, soft ghost notes',
    instruments: 'Rhodes, organ, guitar, horns, strings',
    chords: 'Rich 7ths, 9ths, gospel movement',
    bass: 'Warm, melodic, follows groove',
    mix: 'Warm, organic, vocal-centered',
    keyBias: 'mixed',
    chordColor: 'gospel',
    wave: 'triangle',
    drumFeel: 'soul',
    swing: 0.09,
    drumDrive: 0.55,
    padLevel: 0.27,
    melodyDensity: 0.58,
    brightness: 0.5,
    bassMovement: 0.68,
  },
  Funk: {
    tempoRange: [90, 120],
    drums: 'Tight pocket, syncopated kick and snare',
    instruments: 'Wah guitar, clavinet, horns, organ',
    chords: 'Dominant 7ths, vamps, rhythmic stabs',
    bass: 'Busy, syncopated, slap-friendly',
    mix: 'Dry, punchy, rhythm-forward',
    keyBias: 'major',
    chordColor: 'dominant',
    wave: 'square',
    drumFeel: 'funk',
    swing: 0.05,
    drumDrive: 0.82,
    padLevel: 0.12,
    melodyDensity: 0.72,
    brightness: 0.7,
    bassMovement: 0.92,
  },
  Jazz: {
    tempoRange: [70, 160],
    drums: 'Swing, brushes, ride cymbal focus',
    instruments: 'Piano, upright bass, horns, guitar',
    chords: 'Extended harmony, substitutions, modal colors',
    bass: 'Walking or melodic',
    mix: 'Natural, dynamic, roomy',
    keyBias: 'mixed',
    chordColor: 'jazz',
    wave: 'sine',
    drumFeel: 'jazz',
    swing: 0.18,
    drumDrive: 0.44,
    padLevel: 0.2,
    melodyDensity: 0.66,
    brightness: 0.5,
    bassMovement: 0.88,
  },
  'Neo-Soul': {
    tempoRange: [65, 95],
    drums: 'Laid-back, swung, soft but deep',
    instruments: 'Rhodes, warm pads, guitar, Moog bass',
    chords: 'Dense 9ths, 11ths, 13ths, passing chords',
    bass: 'Smooth, expressive, pocket-heavy',
    mix: 'Warm, intimate, lush',
    keyBias: 'mixed',
    chordColor: 'neo-soul',
    wave: 'sine',
    drumFeel: 'laid-back',
    swing: 0.13,
    drumDrive: 0.52,
    padLevel: 0.34,
    melodyDensity: 0.5,
    brightness: 0.44,
    bassMovement: 0.78,
  },
  Afrobeats: {
    tempoRange: [95, 115],
    drums: 'Syncopated percussion, shakers, rim clicks',
    instruments: 'Plucky guitars, marimbas, soft synths',
    chords: 'Major/minor blend, sunny loops',
    bass: 'Bouncy, melodic, dance-focused',
    mix: 'Bright, percussive, vocal-friendly',
    keyBias: 'major',
    chordColor: 'simple',
    wave: 'triangle',
    drumFeel: 'afrobeats',
    swing: 0.06,
    drumDrive: 0.76,
    padLevel: 0.18,
    melodyDensity: 0.7,
    brightness: 0.78,
    bassMovement: 0.76,
  },
  Dancehall: {
    tempoRange: [85, 105],
    drums: 'Dem bow-inspired kick and snare feel',
    instruments: 'Plucks, organs, brass hits, digital synths',
    chords: 'Minor or bright tropical loops',
    bass: 'Deep, rolling, repetitive',
    mix: 'Loud, punchy, rhythm-forward',
    keyBias: 'mixed',
    chordColor: 'minimal',
    wave: 'square',
    drumFeel: 'dancehall',
    swing: 0.04,
    drumDrive: 0.82,
    padLevel: 0.14,
    melodyDensity: 0.62,
    brightness: 0.74,
    bassMovement: 0.72,
  },
  Reggae: {
    tempoRange: [65, 85],
    drums: 'One-drop, skank rhythm',
    instruments: 'Organ bubble, guitar skanks, horns',
    chords: 'Simple major/minor progressions',
    bass: 'Deep, melodic, central',
    mix: 'Warm, spacious, bass-forward',
    keyBias: 'major',
    chordColor: 'simple',
    wave: 'triangle',
    drumFeel: 'reggae',
    swing: 0.08,
    drumDrive: 0.48,
    padLevel: 0.22,
    melodyDensity: 0.42,
    brightness: 0.48,
    bassMovement: 0.74,
  },
  Drill: {
    tempoRange: [135, 150],
    drums: 'Sliding 808s, sparse kicks, sharp snares',
    instruments: 'Dark pads, bells, choirs, strings',
    chords: 'Minor, tense, cinematic',
    bass: 'Aggressive 808 slides',
    mix: 'Dark, sub-heavy, dry',
    keyBias: 'minor',
    chordColor: 'tense',
    wave: 'saw',
    drumFeel: 'drill',
    swing: 0.04,
    drumDrive: 0.9,
    padLevel: 0.16,
    melodyDensity: 0.34,
    brightness: 0.38,
    bassMovement: 0.9,
  },
  'Jersey Club': {
    tempoRange: [130, 150],
    drums: 'Triplet kick pattern, chopped vocal hits',
    instruments: 'Stabs, samples, bright synths',
    chords: 'Minimal, loop-based',
    bass: 'Short, punchy, rhythmic',
    mix: 'Loud, fast, dance-forward',
    keyBias: 'major',
    chordColor: 'minimal',
    wave: 'square',
    drumFeel: 'jersey',
    swing: 0.02,
    drumDrive: 0.96,
    padLevel: 0.1,
    melodyDensity: 0.82,
    brightness: 0.86,
    bassMovement: 0.78,
  },
  House: {
    tempoRange: [118, 128],
    drums: 'Four-on-the-floor, claps, open hats',
    instruments: 'Piano stabs, pads, synth bass, vocal chops',
    chords: 'Repeating soulful progressions',
    bass: 'Driving, steady, sidechained',
    mix: 'Wide, clean, club-ready',
    keyBias: 'mixed',
    chordColor: 'soulful',
    wave: 'saw',
    drumFeel: 'four-on-floor',
    swing: 0.015,
    drumDrive: 0.9,
    padLevel: 0.18,
    melodyDensity: 0.7,
    brightness: 0.8,
    bassMovement: 0.58,
  },
  Cinematic: {
    tempoRange: [60, 110],
    drums: 'Toms, impacts, sparse percussion',
    instruments: 'Strings, brass, piano, choirs, drones',
    chords: 'Minor, suspended, dramatic',
    bass: 'Deep drones or orchestral low end',
    mix: 'Huge, spacious, dynamic',
    keyBias: 'minor',
    chordColor: 'suspended',
    wave: 'saw',
    drumFeel: 'cinematic',
    swing: 0.01,
    drumDrive: 0.5,
    padLevel: 0.38,
    melodyDensity: 0.38,
    brightness: 0.46,
    bassMovement: 0.34,
  },
  Ambient: {
    tempoRange: [45, 80],
    drums: 'None or minimal pulses',
    instruments: 'Pads, drones, textures, field recordings',
    chords: 'Slow-moving, modal, unresolved',
    bass: 'Subtle, atmospheric',
    mix: 'Wide, spacious, soft',
    keyBias: 'mixed',
    chordColor: 'modal',
    wave: 'sine',
    drumFeel: 'ambient',
    swing: 0,
    drumDrive: 0.1,
    padLevel: 0.46,
    melodyDensity: 0.18,
    brightness: 0.34,
    bassMovement: 0.2,
  },
  Synthwave: {
    tempoRange: [80, 115],
    drums: 'Gated snares, electronic kicks',
    instruments: 'Analog synths, arps, pads, leads',
    chords: 'Minor/major nostalgic progressions',
    bass: 'Pulsing octave bass',
    mix: 'Glossy, retro, wide',
    keyBias: 'mixed',
    chordColor: 'nostalgic',
    wave: 'saw',
    drumFeel: 'synthwave',
    swing: 0.015,
    drumDrive: 0.72,
    padLevel: 0.3,
    melodyDensity: 0.74,
    brightness: 0.68,
    bassMovement: 0.66,
  },
  Rock: {
    tempoRange: [90, 140],
    drums: 'Live kit, strong backbeat',
    instruments: 'Electric guitars, bass guitar, organ',
    chords: 'Power chords, blues-based progressions',
    bass: 'Root-focused, locked with drums',
    mix: 'Guitar-forward, punchy, mid-heavy',
    keyBias: 'mixed',
    chordColor: 'power',
    wave: 'square',
    drumFeel: 'rock',
    swing: 0.02,
    drumDrive: 0.88,
    padLevel: 0.12,
    melodyDensity: 0.62,
    brightness: 0.62,
    bassMovement: 0.36,
  },
  Gospel: {
    tempoRange: [70, 120],
    drums: 'Live pocket, claps, fills',
    instruments: 'Piano, organ, choir, bass guitar',
    chords: 'Big extensions, turnarounds, modulations',
    bass: 'Fluid, follows chord movement',
    mix: 'Warm, powerful, vocal/choir-forward',
    keyBias: 'major',
    chordColor: 'gospel',
    wave: 'triangle',
    drumFeel: 'gospel',
    swing: 0.08,
    drumDrive: 0.66,
    padLevel: 0.28,
    melodyDensity: 0.68,
    brightness: 0.58,
    bassMovement: 0.82,
  },
};

export const moodProfiles = {
  Bright: {
    keyBias: 'major',
    harmony: 'Simple, uplifting',
    tempoBias: 8,
    space: 'Light reverb',
    density: 0.58,
    brightness: 0.9,
    drums: 'Crisp, energetic',
    drumBias: 0.12,
  },
  Warm: {
    keyBias: 'mixed',
    harmony: 'Rich, layered',
    tempoBias: 0,
    space: 'Moderate reverb',
    density: 0.66,
    brightness: 0.48,
    drums: 'Soft, rounded',
    drumBias: -0.08,
  },
  Dreamy: {
    keyBias: 'major',
    harmony: 'Floating, unresolved',
    tempoBias: -5,
    space: 'Heavy reverb and delay',
    density: 0.42,
    brightness: 0.52,
    drums: 'Minimal, airy',
    drumBias: -0.18,
  },
  Dark: {
    keyBias: 'minor',
    harmony: 'Tense, sparse',
    tempoBias: -3,
    space: 'Controlled, less reverb',
    density: 0.35,
    brightness: 0.22,
    drums: 'Hard, sharp',
    drumBias: 0.08,
  },
  Melancholic: {
    keyBias: 'minor',
    harmony: 'Emotional, extended chords',
    tempoBias: -8,
    space: 'Moderate reverb',
    density: 0.5,
    brightness: 0.36,
    drums: 'Soft, subdued',
    drumBias: -0.14,
  },
  Aggressive: {
    keyBias: 'minor',
    harmony: 'Minimal, repetitive',
    tempoBias: 12,
    space: 'Tight, dry',
    density: 0.86,
    brightness: 0.82,
    drums: 'Heavy, punchy',
    drumBias: 0.2,
  },
};

export const stylePresets = Object.keys(styleProfiles);
export const moodPresets = Object.keys(moodProfiles);

const styleAliases = {
  hiphop: 'Hip Hop (Boom Bap)',
  'boom bap': 'Hip Hop (Boom Bap)',
  boombap: 'Hip Hop (Boom Bap)',
  trap: 'Hip Hop (Trap)',
  electronic: 'Electronic / Dance',
  dance: 'Electronic / Dance',
  edm: 'Electronic / Dance',
  lofi: 'Lo-Fi',
  'lo fi': 'Lo-Fi',
  'lo-fi': 'Lo-Fi',
};

function keyFor(value) {
  return String(value || '').toLowerCase().replace(/&/g, 'and').replace(/[^a-z0-9]+/g, ' ').trim();
}

export function styleProfileFor(value) {
  const direct = styleProfiles[value];
  if (direct) return { name: value, ...direct };

  const key = keyFor(value);
  const alias = styleAliases[key];
  if (alias) return { name: alias, ...styleProfiles[alias] };

  const match = stylePresets.find((style) => keyFor(style) === key);
  return { name: match || 'Pop', ...(styleProfiles[match] || styleProfiles.Pop) };
}

export function moodProfileFor(value) {
  const direct = moodProfiles[value];
  if (direct) return { name: value, ...direct };

  const key = keyFor(value);
  const match = moodPresets.find((mood) => keyFor(mood) === key);
  return { name: match || 'Warm', ...(moodProfiles[match] || moodProfiles.Warm) };
}
